name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu

###    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
###      run: whoami && pwd   
      run: docker build . --file Dockerfile --tag flatris-latest:$(date +%s)
